aliases:
    fleeks: cd ~/.local/share/fleek
    k: kubectl
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - tree
    - github-cli
    - yaml-language-server
    - rustup
    - fnm
    - lima
    - k3d
    - kubernetes-helm
    - just
    - dotnet-sdk_8
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - direnv
    - fzf
    - git
    - htop
    - ripgrep
    - starship
    - helix
    - vscode
shell: zsh
systems:
    - arch: aarch64
      home: ""
      hostname: mbp-j12r.local
      os: darwin
      user:
        email: justin.pflueger@fermyon.com
        name: Justin Pflueger
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: j12r
      username: j12r
track: nixos-unstable
unfree: true
users: []
